\subsection{Estudo de Caso 3: A família em dúvida entre dois modelos}

\paragraph{Cenário e Objetivo do Usuário:} Este estudo de caso aborda uma situação comum: uma família, ou um casal com filhos, que está indecisa entre dois modelos de veículos semelhantes, mas com características distintas, como dois sedans populares (ex: Toyota Corolla e Honda Civic). O objetivo é realizar uma comparação exaustiva e detalhada para identificar qual veículo se alinha melhor às suas prioridades, que podem incluir consumo, desempenho, emissões e outros atributos técnicos, buscando uma decisão de compra bem informada e sem arrependimentos.

\paragraph{Ferramenta Escolhida e Justificativa:} Para uma análise comparativa tão abrangente e aprofundada, a \textbf{interface web} é, sem dúvida, a ferramenta mais adequada e poderosa. Diferente do bot de WhatsApp, que prioriza a agilidade em consultas pontuais, a interface web oferece a capacidade de visualizar tabelas detalhadas com múltiplos atributos lado a lado, aplicar e desaplicar filtros de comparação e, crucialmente, consumir o resumo em linguagem natural gerado pelo sistema para uma interpretação qualitativa dos dados. A riqueza visual e interativa da web é indispensável para este nível de detalhe na tomada de decisão.

\paragraph{Execução do Estudo de Caso:}
O usuário inicia a exploração na interface web. Como a família já tem dois modelos específicos em mente, eles podem ir diretamente à seleção. Para o 'Carro 1', a marca 'TOYOTA' é escolhida, seguida do modelo 'COROLLA' e de uma versão específica. De forma análoga, para o 'Carro 2', a marca 'HONDA' é selecionada, o modelo 'CIVIC' e sua respectiva versão. Esse processo de seleção é intuitivo e permite que os usuários foquem nos modelos de seu interesse sem a necessidade de navegar por muitos filtros iniciais (o fluxo seria similar ao ilustrado nas Figuras \ref{fig:sel_marca_1} a \ref{fig:sel_ver_2}, adaptado para os modelos Corolla e Civic).

Após a seleção dos dois veículos, o sistema automaticamente gera e exibe uma \textbf{tabela de comparação detalhada} (Figura \ref{fig:comparativo}). Esta tabela é o cerne da análise para este estudo de caso, pois apresenta uma vasta gama de atributos lado a lado: desde especificações de motor e transmissão, até métricas cruciais como consumo de combustível (cidade/estrada, etanol/gasolina), níveis de poluentes (NMOG+NOx, CO, CHO), emissões de Gás Efeito Estufa (GEE) e classificações de eficiência energética do PBEV. A visualização simultânea dessas informações permite que a família avalie rapidamente os prós e contras de cada modelo em relação aos seus critérios específicos.

Para enriquecer ainda mais a decisão, o sistema então apresenta o \textbf{resumo comparativo em linguagem natural} (Figura \ref{fig:resumo}). Esta funcionalidade, alimentada por dados estruturados e potencialmente por modelos de linguagem (IA), condensa as complexas informações da tabela em uma narrativa fácil de entender. O resumo aponta de forma objetiva qual veículo se destaca em cada métrica relevante (ex: "O Toyota Corolla apresenta um consumo ligeiramente melhor na estrada, enquanto o Honda Civic possui menores emissões de CO2"). Esta "tradução" dos dados técnicos para uma linguagem mais acessível é um diferencial fundamental para famílias que não são especialistas em especificações veiculares.

\paragraph{Conclusão do Estudo de Caso:} Este estudo de caso evidencia o poder da interface web em suportar decisões de compra de veículos que exigem uma análise aprofundada e multifacetada. A capacidade de comparar lado a lado uma vasta quantidade de dados técnicos e ambientais, aliada à funcionalidade de um resumo inteligente em linguagem natural, transforma o processo complexo de escolha entre dois modelos em uma experiência clara e eficiente. O sistema não apenas organiza as informações, mas também as interpreta, capacitando a família a tomar uma decisão consciente e alinhada às suas necessidades e valores, indo além da simples apresentação de dados brutos.